name: 'GitHub ssue Checker'
description: 'GitHub issues checking'
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    required: true 
  labels:
    description: 'GitHub issues labels, you can be specified multi labels with conmma'
    required: true
outputs:
  count:
    description: 'Issue Count'
runs:
  using: 'node12'
  main: 'dist/index.js'