on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: kazupon/sandbox-javascript-github-actions@master
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      if: steps.hello.outputs.count >= 1
      run: echo "The time was ${{ steps.hello.outputs.time }}"