on: [push]

jobs:
  issue:
    runs-on: ubuntu-latest
    name: GitHub Issue checking
    steps:
    - name: GitHub Issue fetch
      id: issue
      uses: kazupon/sandbox-javascript-github-actions@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'l10n'
    - name: l10n issue count
      run: echo "l10n issue count ${{ steps.issue.outputs.count }}"